name: CI/CD Build

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаутим репозиторий
      - uses: actions/checkout@v3

      # 2. Настраиваем Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4. Устанавливаем EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      # 5. Логинимся в Expo (секрет EXPO_TOKEN хранится в Settings → Secrets)
      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      # 6. Запускаем сборку Android
      - name: Build Android (EAS)
        run: eas build --platform android --non-interactive
