name: 📦 CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Сборка Android (EAS)
    runs-on: ubuntu-latest
    # берём токен из секретов репозитория и кладём в env
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: 🛎 Checkout repository
        uses: actions/checkout@v3

      - name: 🥇 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🚀 Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: 🔧 (Optional) Login to Expo (EAS CLI сам возьмёт EXPO_TOKEN)
        # Этот шаг необязателен: EAS CLI автоматически использует EXPO_TOKEN
        # run: eas login --token $EXPO_TOKEN

      - name: 📱 Build Android (non-interactive)
        run: eas build --platform android --non-interactive
